version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: monorepo-ngxp-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - monorepo-network

  # Optional: Redis for caching/sessions
  redis:
    image: redis:7-alpine
    container_name: monorepo-ngxp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - monorepo-network

  # Optional: Adminer for database management
  adminer:
    image: adminer:4
    container_name: monorepo-ngxp-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - monorepo-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  monorepo-network:
    driver: bridge
